routes/web.php
 <?php
 ini_set("memory_limit", "-1");
set_time_limit(0);

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
	return view('welcome');
})->middleware('guest');

Route::get('/admin', function () {
	return view('welcome');
})->middleware('guest');

Route::group(['middleware' => 'auth'], function () {
	Route::get('/job/{id}/previewAdmin', 'JobController@previewAdmin');
	Route::get('/dashboard', 'HomeController@index')->name('dashboard');
	Route::post('/job/{id}/update/{prop}', 'JobController@update')->name('job.update');
	Route::get('/job/export', 'JobController@export')->name('job.export');
	Route::get('/job/active', 'JobController@active');

	Route::post('/job/{id}/updateAll', 'JobController@updateAll')->name('job.updateAll');
	Route::post('/job/{id}/update-avatar', 'JobController@updateAvatar')->name('job.updateAvatar');

	Route::post('/applicants/update', 'JobController@updateApplicantField');
	Route::get('/job/{id}/applicants', 'JobController@applicants');
	Route::get('/job/selectJob/{id}', 'JobController@selectJob');
	Route::post('/job/{id}/postAddress', 'JobController@postAddress');
	Route::get('/job/allTitles', 'JobController@allTitles');
	Route::resource('job', 'JobController');

	Route::get('/messages/{room_id}/{id}', 'ChatController@messages');
	Route::get('/boards/{user_id}', 'ChatController@boards');
	Route::get('/admins', 'ChatController@admins');
	Route::post('/upload', 'ChatController@upload');

	Route::get('/chat', function() {
		return view('admin.chat');
	})->name('chat');

});



Route::get('mail', 'HomeController@mail');

Route::any ( 'sendemail', function () {
	if (Request::get ( 'message' ) != null)
		$data = array (
				'bodyMessage' => Request::get ( 'message' )
		);
	else
		$data [] = '';
	Mail::send ( 'email', $data, function ($message) {

		$message->from ( 'donotreply@demo.com', 'Just Laravel' );

		$message->to ( Request::get ( 'toEmail' ) )->subject ( 'Just Laravel demo email using SendGrid' );
	} );
	return Redirect::back ()->withErrors ( [
			'Your email has been sent successfully'
	] );
});



Route::group(['namespace' => 'Auth', 'middleware' => 'web'], function () {
	Route::get('/auth/{provider}', 'AuthController@getProvider');
	Route::get('/auth/{provider}/callback', 'AuthController@handleProviderCallback');
});


Route::group(['namespace' => 'Auth'], function () {

	Route::get('/login', 'AuthController@getLogin')->name('auth.login');
	Route::post('/login', 'AuthController@postLogin');

	Route::get('/register', 'AuthController@getRegister')->name('auth.register');
	Route::post('/register', 'AuthController@postRegister');

	Route::get('/reset', 'AuthController@getReset')->name('auth.reset');
	Route::post('/reset', 'AuthController@postReset');
	Route::get('/forgot/{token}', 'AuthController@getForgot')->name('auth.forgot');
	Route::post('/forgot/{token}', 'AuthController@postForgot');
});

Route::group(['namespace' => 'Admin', 'middleware' => 'auth'], function () {
	Route::get('/admin/notification/read', 'NotificationController@read')->name('notification.read');
});

Route::group(['namespace' => 'Auth'], function () {
	Route::get('/logout', 'AuthController@getlogout')->middleware('auth')->name('auth.logout');

});

Route::group(['namespace' => 'Company', 'middleware' => 'company'], function () {
	Route::get('/cmp', 'CompanyController@getIndex')->name('cmp.home');

	Route::get('/cmp/profile/view', 'ProfileController@getProfileView')->name('cmp.profile.view');
	Route::get('/cmp/profile', 'ProfileController@getProfile')->name('cmp.profile');
	Route::get('/cmp/profile/logo', function() {
		return view('company.logo');
	})->name('cmp.profile.logo');
	Route::post('/cmp/profile/logo', 'ProfileController@postLogo');
	Route::post('/cmp/profile/state','ProfileController@State');//getting state
	Route::post('/cmp/profile', 'ProfileController@postProfile');
	Route::get('/cmp/profile/reset', 'ProfileController@getReset')->name('cmp.profile.reset');
	Route::post('/cmp/profile/reset', 'CompanyController@postReset');

	Route::get('/cmp/job/{job_id}/delete', 'JobController@delete')->name('job.delete');
	Route::get('/cmp/job/all', 'JobController@getAll')->name('job.all');
	Route::get('/cmp/job/{job_id}/copy', 'JobController@copy')->name('job.copy');
	Route::any('/cmp/job/recent', 'JobController@recent')->name('job.recent');
	Route::get('/cmp/job/progress', 'JobController@progress')->name('job.progress');
	Route::get('/cmp/job/{job_id}/preview', 'JobController@preview')->name('job.preview');
	// Route::resource('/cmp/job', 'JobController');
	Route::resource('/cmp/applicants', 'ApplicantController');

	Route::get('/cmp/applicants/{id}/destroy', 'ApplicantController@destroy')->name('applicants.delete');
	Route::get('/cmp/applicants/{job_id}/exportHired', 'ApplicantController@exportHired')->name('applicants.exportHired');
	// Route::get('/cmp/job/all/export', 'JobController@export')->name('job.export');

	Route::get('/cmp/credits/summary', 'CreditsController@summary')->name('cmp.credits.summary');
	Route::post('/cmp/credits/summary', 'CreditsController@coupon');
	Route::get('/cmp/credits', 'CreditsController@credits')->name('cmp.credits');
	Route::get('/cmp/payments', 'PaymentsController@payments')->name('cmp.payments');
	Route::get('/cmp/package', 'PackagesController@getPurchase')->name('cmp.package');
	Route::post('/cmp/package', 'PackagesController@postPurchase');
	Route::post('/cmp/gst', 'PackagesController@saveGst');
	Route::get('/cmp/redirect', 'PackagesController@getRedirect');
	Route::get('/payment/success', 'PackagesController@success');
	Route::get('/payment/failed', 'PackagesController@failed');
});

Route::group(['namespace' => 'Company', 'middleware' => 'auth'], function () {
	Route::get('/cmp/applicants/{id}/status/{status}', 'ApplicantController@status')->name('applicants.status');
	Route::get('/cmp/applicants/{id}/starred/{starred}', 'ApplicantController@starred')->name('applicants.starred');
	Route::post('/cmp/applicants/{id}/feedback', 'ApplicantController@feedback')->name('applicants.feedback');
});

Route::group(['namespace' => 'Company'], function () {
	Route::resource('/country', 'CountryController', ['except' => ['create', 'store', 'edit', 'update', 'destroy']]);
	Route::get('/cmp/job/{job_id}/hired', 'JobController@hired')->name('job.hired');
	Route::post('/cmp/job/{id}/update/{prop}', 'JobController@update')->name('job.update');
	Route::post('/cmp/job/{job_id}/applicants', 'JobController@applicants')->name('job.applicants');
});

Route::group(['namespace' => 'Admin', 'middleware' => 'admin'], function () {
	Route::get('/admin/dashboard', 'AdminController@dashboard')->name('admin.dashboard');
	Route::get('/admin/users', 'JobController@users')->name('admin.users');
	Route::get('/admin/users/create', 'CompanyController@create')->name('admin.users.create');
	Route::post('/admin/users/register', 'CompanyController@register')->name('admin.users.register');
	Route::get('/admin/users/{user_id}/edit', 'CompanyController@edit')->name('admin.users.edit');
	Route::get('/admin/users/{user_id}/logo', 'CompanyController@logo')->name('admin.users.logo');
	Route::get('/admin/users/{user_id}/reset', 'CompanyController@reset')->name('admin.users.reset');
	Route::post('/admin/users/{user_id}/logo', 'CompanyController@postLogo');
	Route::post('/admin/users/{user_id}/reset', 'CompanyController@postReset');
	Route::post('/admin/users/{user_id}/update', 'CompanyController@update')->name('admin.users.update');
	Route::get('/admin/users/{user_id}/status/{status}', 'CompanyController@status')->name('admin.users.status');
	Route::get('/admin/users/{user_id}/delete', 'CompanyController@delete')->name('admin.users.delete');
	Route::get('/admin/users/{user_id}/credits', 'CreditsController@credits')->name('admin.users.credits');
	Route::get('/admin/users/{user_id}/credits/{badge}', 'CreditsController@giveBadge')->name('admin.users.badge');
	Route::get('/admin/users/{user_id}/credits/manage', 'CreditsController@manage')->name('admin.users.credits.manage');
	Route::get('/admin/users/{user_id}/summary', 'CreditsController@summary')->name('admin.users.summary');
	Route::get('/admin/jobs', 'JobController@jobs')->name('admin.jobs');
	Route::get('/admin/jobs/recent', 'JobController@recent')->name('admin.jobs.recent');
	// Route::get('/admin/jobs/export', 'JobController@export')->name('admin.jobs.export');
	// Route::get('/admin/jobs/create', 'JobController@create')->name('admin.jobs.create');
	// Route::post('/admin/jobs/store', 'JobController@store')->name('admin.jobs.store');
	Route::get('/admin/jobs/{job_id}/delete', 'JobController@delete')->name('admin.jobs.delete');
	Route::get('/admin/jobs/{id}', 'JobController@show')->name('admin.jobs.show');
	Route::get('/admin/map', 'JobController@map')->name('admin.map');

	Route::get('/admin/report/jobs', 'ReportsController@jobs')->name('report.jobs');
	Route::get('/admin/report/users', 'ReportsController@users')->name('report.users');
	Route::get('/admin/report/location', 'ReportsController@location')->name('report.location');
	Route::get('/admin/report/tags', 'ReportsController@tags')->name('report.tags');
	Route::get('/admin/report/industry', 'ReportsController@industry')->name('report.industry');
	Route::get('/admin/template', 'TemplateController@getTemplate')->name('admin.template');
	Route::post('/admin/template', 'TemplateController@postTemplate');
	Route::get('/admin/template/create', 'TemplateController@getCreate')->name('admin.template.create');
	Route::post('/admin/template/create', 'TemplateController@postCreate');
	Route::get('/admin/template/{id}/delete/', 'TemplateController@delete');

resources/views/admin/dashboard.blade.php
@extends('layouts.material')

@section('content')

<div class="row">

	<div class="col s12 m3">
			@include('includes.admin.sidemenu')
	</div>
	<div class="col m9">

		<div id="card-stats">
			<div class="row">
				<div class="col s12 m6 l3">
					<div class="card">
						<div class="card-content  green white-text">
							<p class="card-stats-title"><i class="mdi-social-group-add"></i> New Users</p>
							<h4 class="card-stats-number">{{$total= DB::table('users')->where('role', 2)->get()->count() }}</h4>
							@php
								$yesterday = DB::table('users')->where('role',2)->where('created_at','<',date('Y-m-d'))->get()->count();
								$balance = $total-$yesterday ;
							@endphp
							<p class="card-stats-compare"><i class="mdi-hardware-keyboard-arrow-up"></i>{{ $balance }}% <span class="green-text text-lighten-5">from yesterday</span>
							</p>
						</div>
						<div class="card-action  green darken-2">
							<div id="clients-bar" class="center-align"><canvas width="227" height="25" style="display: inline-block; width: 227px; height: 25px; vertical-align: top;"></canvas></div>
						</div>
					</div>
				</div>
				<div class="col s12 m6 l3">
					<div class="card">
						<div class="card-content pink lighten-1 white-text">
							<p class="card-stats-title"><i class="mdi-editor-insert-drive-file"></i> Active Jobs</p>
							<h4 class="card-stats-number">{{ $total= DB::table('jobs')->where('start_date', '>=', date('Y-m-d'))->get()->count() }}</h4>
							@php
								$previous= DB::table('jobs')->where('start_date', '>=', date("y-m-d", strtotime("-1 months")))->get()->count();
								$balance = $total-$previous ;
							@endphp
							<p class="card-stats-compare"><i class="mdi-hardware-keyboard-arrow-down"></i> {{ $balance }}% <span class="deep-purple-text text-lighten-5">from last month</span>
							</p>
						</div>
						<div class="card-action  pink darken-2">
							<div id="invoice-line" class="center-align"><canvas style="display: inline-block; width: 202px; height: 25px; vertical-align: top;" width="202" height="25"></canvas></div>
						</div>
					</div>
				</div>
				<div class="col s12 m6 l3 hide">
					<div class="card">
						<div class="card-content blue-grey white-text">
							<p class="card-stats-title"><i class="mdi-action-trending-up"></i> Today Profit</p>
							<h4 class="card-stats-number">$0.00</h4>
							<p class="card-stats-compare"><i class="mdi-hardware-keyboard-arrow-up"></i> 0% <span class="blue-grey-text text-lighten-5">from yesterday</span>
							</p>
						</div>
						<div class="card-action blue-grey darken-2">
							<div id="profit-tristate" class="center-align"><canvas width="227" height="25" style="display: inline-block; width: 227px; height: 25px; vertical-align: top;"></canvas></div>
						</div>
					</div>
				</div>
				<div class="col s12 m6 l3 hide">
					<div class="card">
						<div class="card-content purple white-text">
							<p class="card-stats-title"><i class="mdi-editor-attach-money"></i>Total Sales</p>
							<h4 class="card-stats-number">$0.00</h4>
							<p class="card-stats-compare"><i class="mdi-hardware-keyboard-arrow-up"></i> 0% <span class="purple-text text-lighten-5">last month</span>
							</p>
						</div>
						<div class="card-action purple darken-2">
							<div id="sales-compositebar" class="center-align"><canvas width="214" height="25" style="display: inline-block; width: 214px; height: 25px; vertical-align: top;"></canvas></div>
						</div>
					</div>
				</div>
			</div>
		</div>

		@include('includes.alert')

		<div class="row">
			<div class="col s6">
				<div class="header-search-wrapper">
					<i class="mdi-action-search"></i>
					<form role="form" action="{{ route('job.all') }}" name="search" onsubmit="load_more();return false;">
						<input type="text" name="query" class="header-search-input z-depth-2 table-search" placeholder="Search by Job Title or User Name" value="">
					</form>
				</div>
			</div>
		</div>

		<div class="card">
			<div class="card-content hide" id="content1">
				<div class="row">
					<div class="col s6">
						<h4>Recent Jobs</h4>
					</div>
				</div>
				<table class="bordered responsive-table admin-dashboard-table" id="jobs">
					<thead>
						<tr>
							<th>Job Title</th>
							<th>Salary(RM)</th>
							<th>Vacancies</th>
							<!-- <th>User</th>
							<th>Location</th>
							<th>No.of working Days</th>
							<th>Date</th> -->
							<!-- <th>Applicants</th> -->
							<!-- <th>Action</th> -->
						</tr>
					</thead>
					<tbody>

					</tbody>
				</table>
				<br>
				<br>
				<br>
				<br>
			</div>
		</div>
		<div class="col s12 hide" id="content2">
			<div>Showing 1 to <span id="to"></span> of <span id="total"></span> entries</div>
			<div class="row center loadmorediv">
				<button class="btn cyan waves-effect waves-light" onclick="load_more()">View more</button>
			</div>
		</div>
	</div>

</div>

	<div id="preview" class="modal modal-fixed-footer preview-modal">
		<div class="modal-content">
			<!-- <h5 class="center">Preview Job</h5> -->
			<div class="row">

				<div class="col m12 s12">
					<div class="card-content">
						<div class="row">
							<div class="col s12">
								<a href="#!" class="modal-action modal-close close-preview"><i class="mdi-navigation-cancel"></i></a>
							</div>
						</div>
						<div class="row">
							<div class="col s12">

								<img src="#" class="responsive-img" id="Avatar">
							</div>
						</div>
						<div class="row  retail-sales">
							<div class="col s12">
								<h5 id="Title"></h5>
								<P class="" id="Location"></P>
							</div>
						</div>
						<hr>
						<div class="row icon-div">
						<div class="col s2 m2">
						<img src="/images/dollar.png" class="responsive-img">
						</div>
						<div class="col s5 m5">
						<h6 >Salary</h6>
						</div>
						<div class="col s5 m5">
						<h6 id="Salary"></h6>
						</div>
					</div>
					<div class="row icon-div">
						<div class="col s2 m2">
						<img src="/images/calendar.png" class="responsive-img">
						</div>
						<div class="col s5 m5">
						<h6> Working start Date</h6>
						</div>
						<div class="col s5 m5">
						<h6 id="StartDate" </h6>
						</div>
					</div>
					<div class="row icon-div">
						<div class="col s2 m2">
						<img src="/images/watch.png" class="responsive-img">
						</div>
						<div class="col s5 m5">
						<h6>Working Hours</h6>
						</div>
						<div class="col s5 m5">
						<h6 id="StartTime"></h6>
						</div>
					</div>
					<div class="row icon-div">
						<div class="col s2 m2">
						<img src="/images/job_icon.png" class="responsive-img">
						</div>
						<div class="col s5 m5">
						<h6>Type of job</h6>
						</div>
						<div class="col s5 m5">
						<h6 id="Type"></h6>
						</div>
					</div>
						<!--<div class="row icon-div">
							<div class="col s3 m3">
								<img src="/images/dollar.png" class="responsive-img">
								<h6 </h6>
							</div>
							<div class="col s3 m3">
								<img src="/images/calendar.png" class="responsive-img">
								<h6 id=""></h6>
							</div>
							<div class="col s3 m3">
								<img src="/images/watch.png" class="responsive-img">
								<h6 id="">10am-6pm</h6>
							</div>
							<div class="col s3 m3">
								<img src="/images/car_1.png" class="responsive-img">
								<h6>0.9km</h6>
							</div>
						</div>!-->
						<!-- <hr>
						<div class="row about-job">
							<div class="col s12">
								<h5>About this job</h5>
								<p id="About"></p>
							</div>
						</div> -->
						<hr>
						<div class="row role-responsibility">
							<div class="col s12">
								<h5>Role and Responsibilities</h5>
								<textarea class="materialize-textarea border_hide" rows="6" cols="8"></textarea>
							</div>
						</div>
<!-- 						<hr>
						<div class="row about-job">
							<div class="col s12">
								<h5>Tags</h5>
								<ul>
									<li></li>
								</ul>
							</div>
						</div> -->
						<hr>
						<div class="row dress-code">
							<div class="col s12">
								<h5>Dress Code</h5>
								<p id="Uniform"></p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>




@endsection

@section('scripts')
<script src="/js/materialize/plugins/fullcalendar/lib/moment.min.js" type="text/javascript" charset="utf-8"></script>

<script>
	var page = 1, $jobs = [];

	$(document).ready (function(){
		load_more();

		$('[name=query]').change(function (e) {
			page = 1; //refresh
		});
	});

	load_more = function()
	{
		if(page != 0)
		{
			query = $('[name=query]').val();
			$.ajax({
				type : 'get',
				url  : '{{ route('admin.jobs.recent') }}?page='+page+'&query='+query,
			}).done(function(res) {
				fillJobs(res);
			});
		}
	}

	fillJobs = function(result)
	{
		html = '';

		if(!result.next_page_url) {
			$('.loadmorediv').addClass('hide');
		} else {
			$('.loadmorediv').removeClass('hide');
		}

		if(result.data.length == 0){
			// html += '<div class="card job-count0">';
			// html += '<div class="card-content">';
			html += '<h4 class="center"><a href="{{ route('job.create') }}">Post a job to get started.</a></h4>';
			// html += '</div>';
			// html += '</div>';
			$('#content1').html(html);
			$('.loadmorediv').addClass('hide');
			$('#content1').removeClass('hide');
			$('#content1').parent().addClass('job-count0');
		}
		else
		{
			if (page == 1)
			{
				$('#jobs tbody').html('');
			}

			query = $('[name=query]').val();
			if(query != '')
			{
				$('#content1 h4').html("Search results for '"+query+"'");
			}else{
				$('#content1 h4').html("Recent Jobs");
			}


			$('#content1').removeClass('hide');
			$('#content2').removeClass('hide');

			html = '';
			$jobs = result.data;
			result.data.forEach(function(job, index)
			{
				html += '<tr style="display:none;">';
				html += '<td><a href="/job/'+job.id+'/edit"><b>' + job.title + '</b></a></br>'+
						moment(job.start_date).format('DD MMMM, YYYY')+'-'+
						job.state +', '+job.country+'</br>'+
						'<a href="/admin/users/'+job.user_id+'/edit">'+ job.name +'</a></td>';
				/*html += '<td>'+ job.working_hours +'</td>';*/
				html += '<td>'+job.salary+' '+job.salary_unit+'</td>';
				html += '<td><a href="/job/'+job.id+'/applicants">'+job.hired_count+' hired / ' + job.vacancy + '</a></td>';
				/*html += '<td><a href="/job/'+job.id+'/applicants">'+ job.applicants_count +'</a></td>';*/
				html += '<td><ul id="dropdown' + job.id + '" class="dropdown-content">';
				html += '<li><a class="preview" href="#preview" onclick="preview('+index+')">Preview Job</a></li>';
				html += '<li><a href="/job/'+job.id+'/edit">Edit</a></li>';
				html += '<li><a href="/admin/jobs/'+job.id+'/delete" class="DeleteJob">Delete</a></li>';
				html += '</ul><a href="#" class="dropdown-button font-color" data-activates="dropdown'+job.id+'" data-beloworigin="true">More<i class="mdi-navigation-arrow-drop-down"></i></a></td>';
				html += '</tr>';
			});

			$('#jobs tbody').append(html);
			$('tr').show(500);+
			$('#to').html(result.to);
			$('#total').html(result.total);
			$('.dropdown-button').dropdown();
			$('.preview').click(function(){
				$('#preview').openModal();
			});
			page = (result.current_page == result.last_page) ? 0 : page + 1;
		}

	}

	preview = function(index)
	{ 
		console.log($jobs[index]);
		$('#Avatar').attr('src',$jobs[index].cover_picture);;
		$('#Location').html($jobs[index].location);
		$('#Salary').html("RM"+ " "+ $jobs[index].salary +" "+ $jobs[index].salary_unit);
		$('#StartTime').html($jobs[index].start_time +" "+"to"+" "+ $jobs[index].end_time);
		$('#StartDate').html($jobs[index].start_date);
		$('#About').html($jobs[index].about);
		$('#Uniform').html($jobs[index].uniform);
		$('#Title').html($jobs[index].title);
		$('#Type').html($jobs[index].type);
		$('.materialize-textarea').html($jobs[index].requirements);

		/*
		html += '<li>'+ $jobs[index].requirements +'</li>';*/
		/*console.log($jobs[index].tags.name);
		html = '';
		$jobs[index].tags.forEach(function(tag) {
			if (tag.id > 6 && tag.id < 12) {
				html +='<li>'+ tag.name + '</li>';
			}
		});
*/
		$('#preview ul').html(html);
	}

	$(document).ready(function(){
		$('.DeleteJob').click(function(e){
			alert ('abcd');
			/*e.preventDefault();
			var answer = confirm('Do you want to delete this job?');
			if(answer == true){
				location.replace($(this).attr('href'));
			}
			else{
				return false;
			}*/
		});
	});

</script>
@endsection

resources/views/admin/jobs.blade.php
@extends('layouts.material')

@section('content')

<div class="row">

    <div class="col s12 m3">
        <div class="card profile-sidebar">
            @include('includes.admin.sidemenu')
        </div>
    </div>
    <div class="col m9">

        <div class="row">
            <div class="col s10 m4">
                <div class="header-search-wrapper hide-on-med-only">
                    <i class="mdi-action-search"></i>
                    <form role="form" action="{{ route('admin.jobs') }}" name="search" method="GET">
                        <input type="text" name="query" class="header-search-input z-depth-2 table-search" placeholder="Search by Job Title" value="{{ $query }}">
                    </form>
                </div>
            </div>
            <div class="col s12 m8">
                <a href="{{ route('admin.jobs.export') }}?query={{ $query }}" class="btn-flat right teal-text btn-get-csv"><img src="/images/csv-icon.png" class="responsive-img"> Get CSV</a>

                <a href="{{ route('admin.jobs.create') }}" class="waves-effect waves-light btn teal darken-1 right mrg-tb15 admin-postjob-btn">Post Job</a>

                <a href="{{ route('admin.map') }}" class="waves-effect waves-light btn right mrg-tb15 map-btn">Map</a>
            </div>
        </div>

        <div class="card">
                <div class="card-content" id="content1">
                    <h5>All Jobs</h5>
                    <div class="table-scroll">
                        <table class="bordered all-table" id="jobs">
                            <thead>
                                <tr>
                                    <th>Job Title</th>
                                    <th>User</th>
                                    <th>Location</th>
                                    <th>Date</th>
                                    <th>Salary</th>
                                    <th>Vacancies</th>
                                    <th>Applicants</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach ($jobs as $job)
                                <tr>
                                    <td><a href="{{ route('admin.jobs.show', $job->id) }}"><strong>{{$job->title}}</strong></a><br>{{ str_limit($job->about, 20) }}</td>
                                    <td>{{ $job->username }}</td>
                                    <td>{{ $job->location }}</td>
                                    <td>{{ $job->start_date_read }}</td>
                                    <td>{{ $job->salary }}</td>
                                    <td><a href="{{ route('admin.jobs.show', $job->id) }}">{{ $job->hired_count }} hired/ {{$job->vacancy}}</a></td>
                                    <td><a href="{{ route('admin.jobs.show', $job->id) }}">{{ $job->applicants_count }}</a></td>
                                    <td>
                                        Inactive
                                        {{-- <ul id="dropdown{{ $job->iterator }}" class="dropdown-content">
                                            <li><a href="{{ route('job.show', $job->id) }}">Edit</a></li>
                                            <li>
                                            <form action="{{ route('job.destroy', $job->id) }}" method="POST">
                                                <a href="" onclick='$(this).parent().submit();' class="DeleteJob">Delete</a>
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                            </form>
                                            </li>
                                        </ul>
                                        <a href="#" class="btn cyan dropdown-button" data-activates="dropdown{{ $job->iterator }}" data-beloworigin="true">Choose<i class="mdi-navigation-arrow-drop-down right"></i></a> --}}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <br>
                    <br>
                    <div class="col s12 m6 mrg-tb15">
                        <p>Showing {{ ($jobs->firstItem()) ?:0 }} to {{ $jobs->lastItem()?:0 }} of {{ $jobs->total() }} entries</p>
                    </div>
                    <div class="col s12 m6 mrg-tb15">
                        <div class="right">
                            {{ $jobs->links() }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col s12 hide" id="content2">
                <div>Showing 1 to <span id="to"></span> of <span id="total"></span> entries</div>
                <div class="row center loadmorediv">
                    <button class="btn cyan waves-effect waves-light" onclick="load_more()">View more</button>
                </div>
            </div>
    </div>

</div>
@endsection

@section('scripts')
<script src="/js/materialize/plugins/fullcalendar/lib/moment.min.js" type="text/javascript" charset="utf-8"></script>

<script>
    $('.DeleteJob').click(function(e){
        e.preventDefault();
        var answer = confirm('Do you want to delete this Job?');
        if(answer == true){
            location.replace($(this).attr('href'));
        }
        else{
            return false;
        }
    });
</script>
@endsection