routes/web.php
 <?php
 ini_set("memory_limit", "-1");
set_time_limit(0);

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
	return view('welcome');
})->middleware('guest');

Route::get('/admin', function () {
	return view('welcome');
})->middleware('guest');

Route::group(['middleware' => 'auth'], function () {
	Route::get('/job/{id}/previewAdmin', 'JobController@previewAdmin');
	Route::get('/dashboard', 'HomeController@index')->name('dashboard');
	Route::post('/job/{id}/update/{prop}', 'JobController@update')->name('job.update');
	Route::get('/job/export', 'JobController@export')->name('job.export');
	Route::get('/job/active', 'JobController@active');

	Route::post('/job/{id}/updateAll', 'JobController@updateAll')->name('job.updateAll');
	Route::post('/job/{id}/update-avatar', 'JobController@updateAvatar')->name('job.updateAvatar');

	Route::post('/applicants/update', 'JobController@updateApplicantField');
	Route::get('/job/{id}/applicants', 'JobController@applicants');
	Route::get('/job/selectJob/{id}', 'JobController@selectJob');
	Route::post('/job/{id}/postAddress', 'JobController@postAddress');
	Route::get('/job/allTitles', 'JobController@allTitles');
	Route::resource('job', 'JobController');

	Route::get('/messages/{room_id}/{id}', 'ChatController@messages');
	Route::get('/boards/{user_id}', 'ChatController@boards');
	Route::get('/admins', 'ChatController@admins');
	Route::post('/upload', 'ChatController@upload');

	Route::get('/chat', function() {
		return view('admin.chat');
	})->name('chat');

});



Route::get('mail', 'HomeController@mail');

Route::any ( 'sendemail', function () {
	if (Request::get ( 'message' ) != null)
		$data = array (
				'bodyMessage' => Request::get ( 'message' )
		);
	else
		$data [] = '';
	Mail::send ( 'email', $data, function ($message) {

		$message->from ( 'donotreply@demo.com', 'Just Laravel' );

		$message->to ( Request::get ( 'toEmail' ) )->subject ( 'Just Laravel demo email using SendGrid' );
	} );
	return Redirect::back ()->withErrors ( [
			'Your email has been sent successfully'
	] );
});



Route::group(['namespace' => 'Auth', 'middleware' => 'web'], function () {
	Route::get('/auth/{provider}', 'AuthController@getProvider');
	Route::get('/auth/{provider}/callback', 'AuthController@handleProviderCallback');
});


Route::group(['namespace' => 'Auth'], function () {

	Route::get('/login', 'AuthController@getLogin')->name('auth.login');
	Route::post('/login', 'AuthController@postLogin');

	Route::get('/register', 'AuthController@getRegister')->name('auth.register');
	Route::post('/register', 'AuthController@postRegister');

	Route::get('/reset', 'AuthController@getReset')->name('auth.reset');
	Route::post('/reset', 'AuthController@postReset');
	Route::get('/forgot/{token}', 'AuthController@getForgot')->name('auth.forgot');
	Route::post('/forgot/{token}', 'AuthController@postForgot');
});

Route::group(['namespace' => 'Admin', 'middleware' => 'auth'], function () {
	Route::get('/admin/notification/read', 'NotificationController@read')->name('notification.read');
});

Route::group(['namespace' => 'Auth'], function () {
	Route::get('/logout', 'AuthController@getlogout')->middleware('auth')->name('auth.logout');

});

Route::group(['namespace' => 'Company', 'middleware' => 'company'], function () {
	Route::get('/cmp', 'CompanyController@getIndex')->name('cmp.home');

	Route::get('/cmp/profile/view', 'ProfileController@getProfileView')->name('cmp.profile.view');
	Route::get('/cmp/profile', 'ProfileController@getProfile')->name('cmp.profile');
	Route::get('/cmp/profile/logo', function() {
		return view('company.logo');
	})->name('cmp.profile.logo');
	Route::post('/cmp/profile/logo', 'ProfileController@postLogo');
	Route::post('/cmp/profile/state','ProfileController@State');//getting state
	Route::post('/cmp/profile', 'ProfileController@postProfile');
	Route::get('/cmp/profile/reset', 'ProfileController@getReset')->name('cmp.profile.reset');
	Route::post('/cmp/profile/reset', 'CompanyController@postReset');

	Route::get('/cmp/job/{job_id}/delete', 'JobController@delete')->name('job.delete');
	Route::get('/cmp/job/all', 'JobController@getAll')->name('job.all');
	Route::get('/cmp/job/{job_id}/copy', 'JobController@copy')->name('job.copy');
	Route::any('/cmp/job/recent', 'JobController@recent')->name('job.recent');
	Route::get('/cmp/job/progress', 'JobController@progress')->name('job.progress');
	Route::get('/cmp/job/{job_id}/preview', 'JobController@preview')->name('job.preview');
	// Route::resource('/cmp/job', 'JobController');
	Route::resource('/cmp/applicants', 'ApplicantController');

	Route::get('/cmp/applicants/{id}/destroy', 'ApplicantController@destroy')->name('applicants.delete');
	Route::get('/cmp/applicants/{job_id}/exportHired', 'ApplicantController@exportHired')->name('applicants.exportHired');
	// Route::get('/cmp/job/all/export', 'JobController@export')->name('job.export');

	Route::get('/cmp/credits/summary', 'CreditsController@summary')->name('cmp.credits.summary');
	Route::post('/cmp/credits/summary', 'CreditsController@coupon');
	Route::get('/cmp/credits', 'CreditsController@credits')->name('cmp.credits');
	Route::get('/cmp/payments', 'PaymentsController@payments')->name('cmp.payments');
	Route::get('/cmp/package', 'PackagesController@getPurchase')->name('cmp.package');
	Route::post('/cmp/package', 'PackagesController@postPurchase');
	Route::post('/cmp/gst', 'PackagesController@saveGst');
	Route::get('/cmp/redirect', 'PackagesController@getRedirect');
	Route::get('/payment/success', 'PackagesController@success');
	Route::get('/payment/failed', 'PackagesController@failed');
});

Route::group(['namespace' => 'Company', 'middleware' => 'auth'], function () {
	Route::get('/cmp/applicants/{id}/status/{status}', 'ApplicantController@status')->name('applicants.status');
	Route::get('/cmp/applicants/{id}/starred/{starred}', 'ApplicantController@starred')->name('applicants.starred');
	Route::post('/cmp/applicants/{id}/feedback', 'ApplicantController@feedback')->name('applicants.feedback');
});

Route::group(['namespace' => 'Company'], function () {
	Route::resource('/country', 'CountryController', ['except' => ['create', 'store', 'edit', 'update', 'destroy']]);
	Route::get('/cmp/job/{job_id}/hired', 'JobController@hired')->name('job.hired');
	Route::post('/cmp/job/{id}/update/{prop}', 'JobController@update')->name('job.update');
	Route::post('/cmp/job/{job_id}/applicants', 'JobController@applicants')->name('job.applicants');
});

Route::group(['namespace' => 'Admin', 'middleware' => 'admin'], function () {
	Route::get('/admin/dashboard', 'AdminController@dashboard')->name('admin.dashboard');
	Route::get('/admin/users', 'JobController@users')->name('admin.users');
	Route::get('/admin/users/create', 'CompanyController@create')->name('admin.users.create');
	Route::post('/admin/users/register', 'CompanyController@register')->name('admin.users.register');
	Route::get('/admin/users/{user_id}/edit', 'CompanyController@edit')->name('admin.users.edit');
	Route::get('/admin/users/{user_id}/logo', 'CompanyController@logo')->name('admin.users.logo');
	Route::get('/admin/users/{user_id}/reset', 'CompanyController@reset')->name('admin.users.reset');
	Route::post('/admin/users/{user_id}/logo', 'CompanyController@postLogo');
	Route::post('/admin/users/{user_id}/reset', 'CompanyController@postReset');
	Route::post('/admin/users/{user_id}/update', 'CompanyController@update')->name('admin.users.update');
	Route::get('/admin/users/{user_id}/status/{status}', 'CompanyController@status')->name('admin.users.status');
	Route::get('/admin/users/{user_id}/delete', 'CompanyController@delete')->name('admin.users.delete');
	Route::get('/admin/users/{user_id}/credits', 'CreditsController@credits')->name('admin.users.credits');
	Route::get('/admin/users/{user_id}/credits/{badge}', 'CreditsController@giveBadge')->name('admin.users.badge');
	Route::get('/admin/users/{user_id}/credits/manage', 'CreditsController@manage')->name('admin.users.credits.manage');
	Route::get('/admin/users/{user_id}/summary', 'CreditsController@summary')->name('admin.users.summary');
	Route::get('/admin/jobs', 'JobController@jobs')->name('admin.jobs');
	Route::get('/admin/jobs/recent', 'JobController@recent')->name('admin.jobs.recent');
	// Route::get('/admin/jobs/export', 'JobController@export')->name('admin.jobs.export');
	// Route::get('/admin/jobs/create', 'JobController@create')->name('admin.jobs.create');
	// Route::post('/admin/jobs/store', 'JobController@store')->name('admin.jobs.store');
	Route::get('/admin/jobs/{job_id}/delete', 'JobController@delete')->name('admin.jobs.delete');
	Route::get('/admin/jobs/{id}', 'JobController@show')->name('admin.jobs.show');
	Route::get('/admin/map', 'JobController@map')->name('admin.map');

	Route::get('/admin/report/jobs', 'ReportsController@jobs')->name('report.jobs');
	Route::get('/admin/report/users', 'ReportsController@users')->name('report.users');
	Route::get('/admin/report/location', 'ReportsController@location')->name('report.location');
	Route::get('/admin/report/tags', 'ReportsController@tags')->name('report.tags');
	Route::get('/admin/report/industry', 'ReportsController@industry')->name('report.industry');
	Route::get('/admin/template', 'TemplateController@getTemplate')->name('admin.template');
	Route::post('/admin/template', 'TemplateController@postTemplate');
	Route::get('/admin/template/create', 'TemplateController@getCreate')->name('admin.template.create');
	Route::post('/admin/template/create', 'TemplateController@postCreate');
	Route::get('/admin/template/{id}/delete/', 'TemplateController@delete');

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Company extends Model
{
	use SoftDeletes;

	protected $table = 'company';

	protected $guarded = ['id','user_id'];

	protected $fillable = ['user_id',
						   'name',
						   'logo',
						   'type',
						   'description',
						   'building',
						   'address',
						   'city',
						   'state',
						   'country',
						   'zipcode',
						   'website',
						   'tagline',
						   'phone',
						   'industry',
						   'about',
						   'status',
						   'size',
						   'gst_info',
						   'gst_no'
	];

	protected $appends = ['industry_name'];

	protected $dates = ['deleted_at'];

	public function user() {
		return $this->belongsTo('App\User', 'user_id', 'id');
	}

	public function indus() {
			return $this->belongsTo('App\Industry', 'industry', 'id');
			/*dd($this);*/
	}

	public function jobs() {
		return $this->hasMany('App\CmpJob', 'user_id', 'user_id');
	}

	public function orders() {
		return $this->hasMany('App\Orders', 'user_id', 'user_id');
	}

	public function recent() {
		return $this->jobs()->where('start_date','>=', date('Y-m-d'))->orderBy('start_date');
	}

	public function previous() {
		return $this->jobs()->where('start_date','<', date('Y-m-d'));
	}

	public function getImageAttribute()
	{
		return '/uploads/logo/'.$this->attributes['logo'];
	}

	public function getIndustryNameAttribute()
	{
		return $this->belongsTo('App\Industry', 'industry');
	}


	// public function getTypeAttribute()
	// {
	//     switch ($this->attributes['type'])
	//     {
	//         case 'startup':
	//             $type = "Start up";
	//             break;
	//         case 'studio':
	//             $type = "Studio";
	//             break;
	//         case 'small':
	//             $type = "Small Business";
	//             break;
	//         case 'midsized':
	//             $type = "Mid-sized Business";
	//             break;
	//         case 'large':
	//             $type = "Large Organisation";
	//             break;
	//         case 'educational':
	//             $type = "Educational Institution";
	//             break;
	//         case 'nonprofit':
	//             $type = "Non Profit Organisation";
	//             break;
	//         default:
	//             $type = "";
	//             break;
	//     }

	//     return $type;
	// }
}

resources/views/includes/alert.blade.php
@if(Session::has('info'))
<div id="card-alert" class="card green lighten-5">
    <div class="card-content green-text">
        <p>SUCCESS : {{ Session::get('info') }}</p>
    </div>
    <button type="button" class="close green-text" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</div>
@endif

@if(Session::has('success'))
<div id="card-alert" class="card green lighten-5">
    <div class="card-content green-text">
        <p>SUCCESS : {{ Session::get('success') }}</p>
    </div>
    <button type="button" class="close green-text" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</div>
@endif

@if(Session::has('error'))
<div id="card-alert" class="card red lighten-5">
    <div class="card-content red-text">
        <p>ERROR : {{ Session::get('error') }}</p>
    </div>
    <button type="button" class="close red-text" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</div>
@endif

resources/views/includes/breadcrumb.blade.php
<div id="breadcrumbs-wrapper">    
    <div class="container">
        <div class="row">
            <div class="col s12 m12 l12">  
            @if ($breadcrumbs)
                <ol class="breadcrumbs">
                    @foreach ($breadcrumbs as $breadcrumb)
                        @if (!$breadcrumb->last)
                            <li><a href="{{ $breadcrumb->url }}">{{ $breadcrumb->title }}</a></li>
                        @else
                            <li class="active">{{ $breadcrumb->title }}</li>
                        @endif
                    @endforeach
                </ol>
            @endif
            </div>
        </div>
    </div>
</div>

resources/views/includes/footer.blade.php
<!-- START FOOTER -->
<footer class="page-footer">
    <div class="footer-copyright">
        <div class="container">
        <span class="grey-text">Copyright © <?php echo date("Y"); ?> <a class="grey-text" href="" target="_blank">DropPoint</a> All rights reserved.</span>
            <span class="right"><a class="grey-text" href="#"></a></span>
        </div>
    </div>
</footer>
<!-- END FOOTER -->

resources/views/includes/graphsidebar.blade.php
<div class="card profile-sidebar graph-sidebar">
	<ul class="collection">
		<a href="" class="collection-item"><i class="mdi-action-dashboard"></i> Jobs</a>
		<a href="" class="collection-item"><i class="mdi-action-assignment"></i> Users</a>
		<a href="" class="collection-item"><i class="mdi-av-playlist-add"></i> Location</a>
		<a href="" class="collection-item"><i class="mdi-social-group"></i> Tags</a>
		<a href="" class="collection-item"><i class="mdi-social-person-add"></i>Industry</a>
	</ul>
</div>

resources/views/includes/header.blade.php
	@php
		$notifications = \App\Notification::where('user_id', Auth::user()->id)->where('is_read', 0)->get();
	@endphp
	<!-- START HEADER -->
	<!-- <header id="header" class="page-topbar"> -->
		<!-- start header nav-->
		<div class="navbar-fixed admin-nav">
			<nav class="navbar-color">
				<div class="nav-wrapper">
				<div class="row">
					<a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
					<!-- <div class="col s6 m2">
						<ul class="left graph">
							<li><h1 class="logo-wrapper"><a href="{{ route('dashboard') }}" class="brand-logo darken-1">Home</a> <span class="logo-text">Materialize</span></h1></li>
							@if(Auth::user()->isAdmin())
								<li class="graph-right"><h3 class=""><a href="{{ route('report.jobs') }}" class="">Reports</a></h3></li>
							@endif
						</ul>
					</div> -->
					<div class="col s12 m12">
						<a href="{{ route('dashboard') }}" class="main-logo"><img src="{{ env('APP_ICON') }}" alt="" class="responsive-img" /></a>
				      	<ul id="nav-mobile" class="hide-on-med-and-down left">
							<!-- <li><a href="{{ route('dashboard') }}" class="darken-1"><img src='{{{ asset('images/icon and typeface/256.png') }}}' alt="" class="responsive-img" /></a></li> -->
							@if(Auth::user()->isAdmin())
								<li><a href="{{ route('report.jobs') }}" class="">Reports</a></li>
							@endif

					        <li class="active"><a href="/dashboard">Jobs</a></li>
					        <li><a href="/chat">Support</a></li>
				      	</ul>

				      	<ul class="side-nav" id="mobile-demo">
							<li><a href="{{ route('dashboard') }}" class="darken-1">Home</a></li>
							@if(Auth::user()->isAdmin())
								<li><a href="{{ route('report.jobs') }}" class="">Reports</a></li>
							@endif
					        <li class="active"><a href="/dashboard">Jobs</a></li>
					        <li><a href="/chat">Support</a></li>
				      	</ul>
						<ul class="right">
							<li>
								<a href="javascript:void(0);" class="waves-effect waves-block waves-light notification-button" data-activates="notifications-dropdown" data-hover="false" onclick="markRead();"><i class="mdi-social-notifications" data-hover="false"><small class="notification-badge notification-count">{{ count($notifications) }}</small></i>
								</a>
								<ul id="notifications-dropdown" class="dropdown-content" style="white-space: nowrap; position: absolute; top: 64px; left: 969px; opacity: 1; display: none;">
									<li>
									<h5>NOTIFICATIONS <span class="new badge notification-count">{{ count($notifications) }}</span></h5>
									</li>
									<li class="divider"></li>
									@foreach(\App\Notification::where('user_id', Auth::user()->id)->get() as $notification)
										<li>
											<a href="{{(str_contains($notification->message, ['RoomID'])) ? '/chat': '#'}}"><i class="mdi-action-trending-up"></i> {!!$notification->message!!}</a>
											<time class="media-meta" datetime="{{$notification->ago}}">{{$notification->ago}}
											</time>
										</li>
									@endforeach


									{{-- <li>
									<a href="#!"><i class="mdi-action-add-shopping-cart"></i> A new order has been placed!</a>
									<time class="media-meta" datetime="2015-06-12T20:50:48+08:00">2 hours ago</time>
									</li>
									<li>
									<a href="#!"><i class="mdi-action-stars"></i> Completed the task</a>
									<time class="media-meta" datetime="2015-06-12T20:50:48+08:00">3 days ago</time>
									</li>
									<li>
									<a href="#!"><i class="mdi-action-settings"></i> Settings updated</a>
									<time class="media-meta" datetime="2015-06-12T20:50:48+08:00">4 days ago</time>
									</li>
									<li>
									<a href="#!"><i class="mdi-editor-insert-invitation"></i> Director meeting started</a>
									<time class="media-meta" datetime="2015-06-12T20:50:48+08:00">6 days ago</time>
									</li>
									<li>
									<a href="#!"><i class="mdi-action-trending-up"></i> Generate monthly report</a>
									<time class="media-meta" datetime="2015-06-12T20:50:48+08:00">1 week ago</time>
									</li> --}}
								</ul>
							</li>
							<li>
								<ul id="profile-dropdown" class="dropdown-content">
									@if(Auth::user()->isCompany())
										<li><a href="{{ route('cmp.profile') }}"> <i class="mdi-action-account-circle"></i> Profile</a></li>
									@elseif(Auth::user()->isAdmin())
										{{-- <li><a href="{{ route('cmp.profile') }}"> <i class="mdi-action-account-circle"></i> Profile</a></li> --}}
									@endif
										<li><a href="{{ route('dashboard') }}"> <i class="mdi-action-assignment"></i> Jobs</a></li>
									<li class="divider"></li>
									<li><a href="{{ route('auth.logout') }}"> <i class="mdi-hardware-keyboard-tab"></i> Logout</a></li>
								</ul>
								<a href="#" class="dropdown-button waves-effect waves-light"  data-beloworigin="true" data-activates="profile-dropdown">
									<!-- <span class="header-user-profile-pic-box">
										<span class="header-user-profile-pic">
											<img src="{{ (Auth::user()->isCompany()) ? Auth::user()->company->image : '/uploads/logo/avatar.jpg' }}" alt="" class="circle responsive-img valign profile-image">
										</span>
									</span> -->
									<span class="header-user-name">{{ title_case(Auth::user()->name) }} <i class="mdi-navigation-arrow-drop-down right"></i></span>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</nav>
	</div>
	<!-- end header nav-->
	<!-- </header> -->
	<!-- END HEADER -->

	<script type="text/javascript">
		markRead = function() {
			console.log('marking read')
			// return;
			$.ajax({
				type : 'get',
				url  : '/admin/notification/read',
			}).done(function(res) {
				setTimeout(function(){
					$('.notification-count').html(0);
				},1000);
			});
		}
	</script>

resources/views/includes/mobile-header.blade.php
<script type="text/javascript">
	$( document ).ready(function(){
		$(".button-collapse").sideNav();
	});
</script>

resources/views/includes/sidemenu.blade.php
<div class="card profile-sidebar">
	@if(str_contains(url()->current(), 'profile') || str_contains(url()->current(), 'credits') || str_contains(url()->current(), 'payments'))
		<div class="card-content">
			<div class="profile-userpic"> <img src="{{ Auth::user()->company->logo }}" class="responsive-img" alt=""> </div>
			<div class="profile-user-detials">
				<div class="profile-user-name"> {{ title_case(Auth::user()->name) }} </div>
				<div class="profile-user-designation"> {{ Auth::user()->role_name }} </div>
			</div>
		</div>
		<ul class="collection">
			<a href="{{ route('cmp.profile') }}" class="collection-item{{ setActive('cmp.profile') }}"><i class="mdi-image-timer-auto"></i> About You</a>
			<a href="{{ route('cmp.profile.logo') }}" class="collection-item{{ setActive('cmp.profile.logo') }}"><i class="mdi-image-photo"></i> Upload Logo</a>
			<a href="{{ route('cmp.profile.reset') }}" class="collection-item{{ setActive('cmp.profile.reset') }}"><i class="mdi-communication-vpn-key"></i> Reset Password</a>
			<a href="{{route('cmp.credits.summary')}}" class="collection-item{{ setActive('cmp.credits.summary') }}"><i class="mdi-action-view-list"></i> Credit Summary</a>
			<a href="{{route('cmp.credits')}}" class="collection-item{{ setActive('cmp.credits') }}"><i class="mdi-action-account-balance-wallet"></i> Transaction History</a>
			<a href="{{route('cmp.payments')}}" class="collection-item{{ setActive('cmp.payments') }}"><i class="mdi-action-payment"></i>Payment History</a>
			<a href="{{route('chat')}}" class="collection-item{{ setActive('chat') }}"><i class="mdi-action-payment"></i>Chat</a>
		</ul>
	@else
		<h6><strong>Jobs</strong></h6>
		<ul class="collection">
			<a href="{{ route('job.index') }}" class="collection-item{{ setActive('job.index') }}"><i class="mdi-action-assignment"></i> All Jobs</a>
			<a href="{{ route('job.create') }}" class="collection-item{{ setActive('job.create') }}"><i class="mdi-av-playlist-add"></i> Add Job</a>
			<a href="{{ route('chat') }}" class="collection-item{{ setActive('chat') }}"><i class="mdi-av-playlist-add"></i> Chat</a>
		</ul>
	@endif
</div>

resources/views/includes/theme.blade.php
@if(env('APP_COLOR') == 'RED')
	<link href="{{asset('css/themes/red.css')}}" type="text/css" rel="stylesheet" media="screen,projection">
@elseif(env('APP_COLOR') == 'BLUE')
	<link href="{{asset('css/themes/blue.css')}}" type="text/css" rel="stylesheet" media="screen,projection">
@elseif(env('APP_COLOR') == 'BLACK')
	<link href="{{asset('css/themes/black.css')}}" type="text/css" rel="stylesheet" media="screen,projection">
@elseif(env('APP_COLOR') == 'CORAL')
	<link href="{{asset('css/themes/coral.css')}}" type="text/css" rel="stylesheet" media="screen,projection">
@elseif(env('APP_COLOR') == 'PURPLE')
	<link href="{{asset('css/themes/purple.css')}}" type="text/css" rel="stylesheet" media="screen,projection">
@endif